### ISSUE TITLE
An applet that will miss for Cinnamon :(

### ISSUE THREAD

**Issue by melmelissa** [marmistrz/bumblebee-indicator-cinnamon#1]
Hello
Really bad that the applet "" Simple Bumblebee Indicator "" is no longer available for Cinnamon.
I just installed ArchLinux Cinnamon and alas my favorite applet is no longer available for download.
It was the only one that was really simple without unnecessary options and that was 100% functional without any bugs ..
A manual installation by recovering the .zip, alas not working :(
Or I do not know how to do: /

Really bad, it was great this little applet :(
It was the only one I found indispensable to monitor the state of GPUs
I may be the only user, but I was satisfied.
I will miss it...

**Comment by marmistrz** [comment]
Hi, 
Please use bumblebee@pdcurtis. My applet has become its strict subset, so we decided to remove it.

See this PR: https://github.com/linuxmint/cinnamon-spices-applets/pull/1162#event-1209045913 and the discussion linked further.

I'll add an information to the README.

It's great to know someone liked my applet :)
